"""Strategy lifecycle model — pure, testable transforms.

The Strategy Profiles registry historically used a free ``status`` field with a
mix of readiness states (``ready``/``in_progress``/``rejected``/``archived`` …).
This module formalizes a single 4-state *lifecycle* on top of that field so the
UI and portfolio logic can reason about one canonical dimension:

  1. ``trial``           — Испытание. Strategy under evaluation; reserves a
                           portfolio cell with a remaining-term note. Every
                           trial carries an individual ``trial_plan`` (time /
                           condition / effort / gates) decided at planning time.
  2. ``approved_demo``   — Утверждено для демо. Counts in the portfolio. Carries
                           a ``demo_plan`` (forecast + horizon) and a live↔history
                           reconciliation.
  3. ``approved_live``   — Утверждено для реальной торговли. Only reachable after
                           a profitable demo period.
  4. ``failed_archived`` — Провалено → Архив. Removed from NinjaTrader (AI
                           sandbox auto-quarantine; production flag + checklist +
                           deletion) and written to a do-not-recreate registry
                           keyed by a stable fingerprint.

A second orthogonal dimension is ``origin``: ``production`` (hand-developed) vs
``ai_lab`` (generated by the local LM Studio AI lab). The UI shows an "AI / LM
Studio" badge and keeps the two streams visually separate.

No IO here. Runtime/registry reads live in jobqueue/server so these functions
stay unit-testable in tests/test_strategy_lifecycle.py.
"""
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple


# --- Lifecycle states -------------------------------------------------------

TRIAL = "trial"
APPROVED_DEMO = "approved_demo"
APPROVED_LIVE = "approved_live"
FAILED_ARCHIVED = "failed_archived"

LIFECYCLE_ORDER: Tuple[str, ...] = (TRIAL, APPROVED_DEMO, APPROVED_LIVE, FAILED_ARCHIVED)
LIFECYCLE_SET = frozenset(LIFECYCLE_ORDER)

LIFECYCLE_LABELS: Dict[str, str] = {
    TRIAL: "Испытание",
    APPROVED_DEMO: "Утверждено для демо",
    APPROVED_LIVE: "Утверждено для реальной торговли",
    FAILED_ARCHIVED: "Провалено → Архив",
}

# Map legacy/free ``status`` values onto the canonical lifecycle.
_STATUS_TO_LIFECYCLE: Dict[str, str] = {
    "ready": APPROVED_DEMO,
    "paper_ready": APPROVED_DEMO,
    "approved_demo": APPROVED_DEMO,
    "demo_approved": APPROVED_DEMO,
    "approved_live": APPROVED_LIVE,
    "live": APPROVED_LIVE,
    "live_approved": APPROVED_LIVE,
    "in_progress": TRIAL,
    "paper_candidate": TRIAL,
    "candidate": TRIAL,
    "demo_trial": TRIAL,
    "research_baseline": TRIAL,
    "baseline": TRIAL,
    "rejected": FAILED_ARCHIVED,
    "archived": FAILED_ARCHIVED,
}

# Lifecycle states that occupy a real, counted portfolio cell.
PORTFOLIO_COUNTED = frozenset({APPROVED_DEMO, APPROVED_LIVE})
# Lifecycle states that reserve a portfolio cell (shown, but flagged).
PORTFOLIO_RESERVED = frozenset({TRIAL})

# Representative legacy ``status`` for each lifecycle, so older consumers
# (trading launch gate, coverage, portfolio counting) keep working when only
# ``lifecycle`` is set by the operator.
_LIFECYCLE_TO_STATUS: Dict[str, str] = {
    TRIAL: "in_progress",
    APPROVED_DEMO: "ready",
    APPROVED_LIVE: "ready",
    FAILED_ARCHIVED: "archived",
}


def status_for_lifecycle(lifecycle: str) -> str:
    """Best legacy ``status`` to keep in sync with a lifecycle value."""
    return _LIFECYCLE_TO_STATUS.get(str(lifecycle or "").strip().lower(), "in_progress")


# --- AI Lab experiment status -> lifecycle ----------------------------------
#
# The AI Strategy Lab runs each idea through its own status machine (see
# app/ai_lab/registry.py). These map onto the same 4 portfolio lifecycle stages
# so AI-built strategies show up in the lifecycle board next to production ones.

# Still being researched / evaluated (Испытание).
AI_TRIAL_STATUSES = frozenset({
    "draft", "generating", "generated", "awaiting_compile", "catalog_visible",
    "backtesting", "backtest_done", "analysis_ready", "mutation_planned",
    "mutation_candidate", "sandbox_candidate", "champion_candidate",
    "human_review_candidate",
})
# Promoted into the working portfolio (Утверждено для демо).
AI_APPROVED_DEMO_STATUSES = frozenset({"portfolio_contributor"})
# Everything else terminal (rejected/cancelled/*_failed/blocked/archived) is a
# failed/archived AI experiment.


def lifecycle_for_ai_status(status: Any) -> str:
    """Map one AI Lab experiment ``status`` onto a portfolio lifecycle stage."""
    s = str(status or "").strip().lower()
    if s in AI_APPROVED_DEMO_STATUSES:
        return APPROVED_DEMO
    if s in AI_TRIAL_STATUSES:
        return TRIAL
    return FAILED_ARCHIVED


# Russian stage labels for the AI trial sub-status shown on hover/cards.
AI_STATUS_LABELS_RU: Dict[str, str] = {
    "draft": "черновик",
    "generating": "генерация кода",
    "generated": "код сгенерирован",
    "awaiting_compile": "ожидает компиляции",
    "catalog_visible": "виден в каталоге",
    "backtesting": "идёт бэктест",
    "backtest_done": "бэктест завершён",
    "analysis_ready": "анализ готов",
    "mutation_planned": "запланирована мутация",
    "mutation_candidate": "кандидат на мутацию",
    "sandbox_candidate": "кандидат sandbox",
    "champion_candidate": "кандидат-чемпион",
    "human_review_candidate": "на ручной проверке",
    "portfolio_contributor": "в портфеле",
    "rejected": "отклонено",
    "cancelled": "отменено",
    "validation_failed": "ошибка валидации",
    "compile_failed": "ошибка компиляции",
    "compile_failed_after_fix_loop": "ошибка компиляции (после фикс-цикла)",
    "awaiting_compile_timeout": "таймаут компиляции",
    "blocked_by_real_environment_issue": "блок: окружение",
    "blocked_lm_studio": "блок: LM Studio",
    "backtest_failed": "ошибка бэктеста",
    "pipeline_failed": "сбой пайплайна",
    "archived": "архив",
}


def ai_status_label_ru(status: Any) -> str:
    s = str(status or "").strip().lower()
    return AI_STATUS_LABELS_RU.get(s, s or "—")


# --- Origin (production vs AI lab) -----------------------------------------

ORIGIN_PRODUCTION = "production"
ORIGIN_AI_LAB = "ai_lab"

ORIGIN_LABELS: Dict[str, str] = {
    ORIGIN_PRODUCTION: "Production",
    ORIGIN_AI_LAB: "AI / LM Studio",
}

_AI_EXPERIMENT_RE = re.compile(r"^EXP-\d{8}-\d{4}$", re.IGNORECASE)
_AI_CELL_RE = re.compile(r"^AI-CELL-[A-Z0-9]+-\d{3}$", re.IGNORECASE)


def classify_lifecycle(profile: Dict[str, Any]) -> str:
    """Resolve the canonical lifecycle state for one profile.

    Explicit ``lifecycle`` wins; otherwise the legacy ``status`` is mapped.
    Unknown values fall back to ``trial`` (the safe, non-portfolio state).
    """
    explicit = str((profile or {}).get("lifecycle") or "").strip().lower()
    if explicit in LIFECYCLE_SET:
        return explicit
    status = str((profile or {}).get("status") or "").strip().lower()
    if status in _STATUS_TO_LIFECYCLE:
        return _STATUS_TO_LIFECYCLE[status]
    # Archive heuristics: matrix_hidden or an archive block means failed/archived.
    if profile and (profile.get("matrix_hidden") or profile.get("failed_archive")
                    or profile.get("archive_reason")):
        return FAILED_ARCHIVED
    return TRIAL


def detect_origin(profile: Dict[str, Any]) -> str:
    """Decide whether a profile came from the AI lab or manual production."""
    explicit = str((profile or {}).get("origin") or "").strip().lower()
    if explicit in (ORIGIN_PRODUCTION, ORIGIN_AI_LAB):
        return explicit
    if not profile:
        return ORIGIN_PRODUCTION
    if isinstance(profile.get("ai_lab"), dict) and profile.get("ai_lab"):
        return ORIGIN_AI_LAB
    created_by = str(profile.get("created_by") or "").strip().lower()
    if created_by in ("ai", "ai_lab", "lm_studio", "lmstudio"):
        return ORIGIN_AI_LAB
    for key in ("ai_experiment_id", "experiment_id", "ai_cell_id"):
        value = str(profile.get(key) or "").strip()
        if _AI_EXPERIMENT_RE.match(value) or _AI_CELL_RE.match(value):
            return ORIGIN_AI_LAB
    return ORIGIN_PRODUCTION


def is_ai_lab(profile: Dict[str, Any]) -> bool:
    return detect_origin(profile) == ORIGIN_AI_LAB


# --- Date helpers -----------------------------------------------------------

def parse_iso(value: Any) -> Optional[datetime]:
    """Parse an ISO-8601 timestamp (with or without ``Z``) into aware UTC."""
    text = str(value or "").strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(text)
    except ValueError:
        # Date-only fallback (YYYY-MM-DD).
        try:
            dt = datetime.strptime(text[:10], "%Y-%m-%d")
        except ValueError:
            return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


_UNIT_DAYS: Dict[str, float] = {
    "day": 1.0, "days": 1.0, "дн": 1.0, "день": 1.0, "дня": 1.0, "дней": 1.0,
    "week": 7.0, "weeks": 7.0, "нед": 7.0, "неделя": 7.0, "недели": 7.0, "недель": 7.0,
    "month": 30.0, "months": 30.0, "мес": 30.0, "месяц": 30.0, "месяца": 30.0, "месяцев": 30.0,
}


def _duration_days(duration: Any) -> Optional[float]:
    if not isinstance(duration, dict):
        return None
    try:
        value = float(duration.get("value"))
    except (TypeError, ValueError):
        return None
    unit = str(duration.get("unit") or "days").strip().lower()
    return value * _UNIT_DAYS.get(unit, 1.0)


def _plural_days(n: int) -> str:
    n = abs(n)
    if 11 <= (n % 100) <= 14:
        return "дней"
    last = n % 10
    if last == 1:
        return "день"
    if 2 <= last <= 4:
        return "дня"
    return "дней"


# --- Trial / demo plan progress --------------------------------------------

def compute_plan_progress(plan: Any, now: Optional[datetime] = None) -> Dict[str, Any]:
    """Compute remaining-term/progress for a trial_plan or demo_plan.

    Returns ``{state, label, remaining_days, percent, basis}`` where ``state`` is
    one of ``running`` / ``completed`` / ``no_data``. The ``basis`` may be
    ``time`` (start+end/duration), ``gates``/``effort`` (completed vs total) or
    ``condition`` (free-form criterion).
    """
    now = now or datetime.now(timezone.utc)
    if not isinstance(plan, dict) or not plan:
        return {"state": "no_data", "label": "нет данных", "remaining_days": None,
                "percent": None, "basis": None}

    basis = str(plan.get("basis") or "").strip().lower()

    # Gate / effort based progress.
    total = plan.get("total_gates", plan.get("total"))
    done = plan.get("completed_gates", plan.get("completed"))
    if basis in ("gates", "effort") or (total is not None and basis not in ("time",)):
        try:
            total_n = int(total)
            done_n = int(done or 0)
        except (TypeError, ValueError):
            total_n, done_n = 0, 0
        if total_n > 0:
            done_n = max(0, min(done_n, total_n))
            percent = round(100.0 * done_n / total_n, 1)
            state = "completed" if done_n >= total_n else "running"
            unit_word = "усилий" if basis == "effort" else "гейтов"
            label = (f"завершено: {done_n}/{total_n} {unit_word}"
                     if state == "completed" else f"осталось: {total_n - done_n}/{total_n} {unit_word}")
            return {"state": state, "label": label, "remaining_days": None,
                    "percent": percent, "basis": basis or "gates"}

    # Time based progress.
    start = parse_iso(plan.get("started_at_utc") or plan.get("start_utc"))
    end = parse_iso(plan.get("planned_end_utc") or plan.get("end_utc"))
    if end is None and start is not None:
        dur = _duration_days(plan.get("duration"))
        if dur is not None:
            from datetime import timedelta
            end = start + timedelta(days=dur)
    if end is not None:
        remaining_days = int((end - now).total_seconds() // 86400)
        if remaining_days <= 0:
            return {"state": "completed",
                    "label": "срок испытания завершён",
                    "remaining_days": remaining_days, "percent": 100.0, "basis": "time"}
        percent = None
        if start is not None and end > start:
            elapsed = (now - start).total_seconds()
            span = (end - start).total_seconds()
            percent = round(max(0.0, min(100.0, 100.0 * elapsed / span)), 1)
        return {"state": "running",
                "label": f"осталось {remaining_days} {_plural_days(remaining_days)}",
                "remaining_days": remaining_days, "percent": percent, "basis": "time"}

    # Free-form condition.
    condition = str(plan.get("condition_text") or plan.get("condition") or "").strip()
    if condition:
        return {"state": "running", "label": f"по условию: {condition}",
                "remaining_days": None, "percent": None, "basis": "condition"}

    return {"state": "no_data", "label": "нет данных", "remaining_days": None,
            "percent": None, "basis": basis or None}


# --- Demo reconciliation (history avg vs live fact) -------------------------

def reconcile(expected_net: Optional[float],
              actual_net: Optional[float],
              *,
              tolerance: float = 0.5,
              has_sample: bool = True) -> Dict[str, Any]:
    """Compare an expected (historical/forecast) net against the live fact.

    * ``on_track``        — live net >= expected * (1 - tolerance) and >= 0.
    * ``underperforming`` — live net below the tolerated band or negative.
    * ``insufficient``    — no live sample or no expectation to compare against.

    ``tolerance`` is a fraction (0.5 = within 50% of the historical average).
    """
    if expected_net is None or actual_net is None or not has_sample:
        return {"verdict": "insufficient", "expected_net": expected_net,
                "actual_net": actual_net, "delta": None, "ratio": None}
    delta = round(actual_net - expected_net, 4)
    ratio = round(actual_net / expected_net, 4) if expected_net else None
    floor = expected_net * (1.0 - tolerance)
    if actual_net >= 0 and (expected_net <= 0 or actual_net >= floor):
        verdict = "on_track"
    else:
        verdict = "underperforming"
    return {"verdict": verdict, "expected_net": round(expected_net, 4),
            "actual_net": round(actual_net, 4), "delta": delta, "ratio": ratio}


def demo_expected_net(profile: Dict[str, Any]) -> Optional[float]:
    """Best available "expected" net for a demo period.

    Priority: explicit ``demo_plan.forecast_net`` → historical average per
    period (``approved_demo.historical.avg_net_per_period``).
    """
    plan = (profile or {}).get("demo_plan")
    if isinstance(plan, dict):
        try:
            return float(plan.get("forecast_net"))
        except (TypeError, ValueError):
            pass
    demo = (profile or {}).get("approved_demo")
    if isinstance(demo, dict):
        hist = demo.get("historical")
        if isinstance(hist, dict):
            try:
                return float(hist.get("avg_net_per_period"))
            except (TypeError, ValueError):
                pass
    return None


# --- Archive fingerprint (do-not-recreate key) ------------------------------

_FINGERPRINT_PARAM_KEYS = (
    "EnableLong", "EnableShort", "TradeStartTime", "TradeEndTime",
    "AtrStopMult", "RewardRiskRatio", "MinStopTicks", "MaxStopTicks",
)


def _normalize_root(value: Any) -> str:
    text = str(value or "").strip().upper()
    match = re.match(r"^([A-Z0-9]+)", text)
    return match.group(1) if match else ""


def archive_fingerprint(profile: Dict[str, Any]) -> str:
    """Stable identity for a strategy *idea*, used to prevent re-creation.

    Combines the strategy class, instrument root, timeframe and a small set of
    defining locked parameters. Two profiles describing the same idea map to the
    same fingerprint even if names/ids differ.
    """
    profile = profile or {}
    cls = str(profile.get("deploy_strategy_class")
              or profile.get("strategy_class")
              or profile.get("strategy") or "").strip().lower()
    root = _normalize_root(profile.get("instrument") or profile.get("current_contract"))
    timeframe = str(profile.get("timeframe") or "").strip().lower()
    params = profile.get("locked_parameters")
    param_sig: Dict[str, Any] = {}
    if isinstance(params, dict):
        for key in _FINGERPRINT_PARAM_KEYS:
            if key in params:
                param_sig[key] = params[key]
    payload = json.dumps(
        {"cls": cls, "root": root, "tf": timeframe, "p": param_sig},
        sort_keys=True, ensure_ascii=False,
    )
    digest = hashlib.sha1(payload.encode("utf-8")).hexdigest()[:16]
    return f"fp_{digest}"


# --- Profile annotation -----------------------------------------------------

def annotate(profile: Dict[str, Any], now: Optional[datetime] = None) -> Dict[str, Any]:
    """Return a shallow copy of ``profile`` enriched with derived lifecycle UI
    fields. Pure: never mutates the input.
    """
    out = dict(profile or {})
    lifecycle = classify_lifecycle(out)
    origin = detect_origin(out)
    out["lifecycle"] = lifecycle
    out["lifecycle_label"] = LIFECYCLE_LABELS[lifecycle]
    out["origin"] = origin
    out["origin_label"] = ORIGIN_LABELS[origin]
    out["is_ai_lab"] = origin == ORIGIN_AI_LAB

    if lifecycle == TRIAL:
        out["trial_progress"] = compute_plan_progress(out.get("trial_plan"), now)
        out["portfolio_reserved"] = True
    elif lifecycle in (APPROVED_DEMO, APPROVED_LIVE):
        plan = out.get("demo_plan")
        if isinstance(plan, dict):
            out["demo_progress"] = compute_plan_progress(plan, now)
        recon = out.get("demo_reconciliation")
        if not isinstance(recon, dict):
            expected = demo_expected_net(out)
            live = out.get("approved_demo")
            actual = None
            if isinstance(live, dict) and isinstance(live.get("live"), dict):
                try:
                    actual = float(live["live"].get("net_pnl"))
                except (TypeError, ValueError):
                    actual = None
            if expected is not None or actual is not None:
                out["demo_reconciliation"] = reconcile(
                    expected, actual, has_sample=actual is not None)
    return out
