using NinjaTrader.NinjaScript.Strategies;

namespace NinjaTrader.NinjaScript.Strategies
{
    public abstract partial class NTASessionVwapReclaimScalper
    {
        protected void LockIndexDefaults()
        {
            StartingCapital = 2000.0;
            BarsRequiredToTrade = 10;
            IntradayOnly = true;
            MaxContractsByCapital = 20;
            InstrumentStatus = "allowed";
            MarginSourceBroker = "NinjaTrader";
            TradeStartTime = 635;
            TradeEndTime = 830;
            ForceFlatTime = 1245;
            OpeningRangeStartTime = 630;
            OpeningRangeMinutes = 5;
            EmaFastPeriod = 9;
            EmaSlowPeriod = 34;
            AtrPeriod = 14;
            AdxPeriod = 14;
            MinAdx = 0.0;
            VolumeSmaPeriod = 20;
            MinVolumeFactor = 1.10;
            MinBodyRangePct = 0.45;
            MinCloseLocationPct = 0.60;
            VwapMode = SessionVwapMode.TypicalPrice;
            VwapSlopeLookback = 8;
            MinVwapSlopeTicks = 1.0;
            VwapReclaimBufferTicks = 1;
            VwapChopBandTicks = 4;
            VwapCrossLookback = 12;
            MaxVwapCrosses = 3;
            MinEmaSpreadTicks = 2;
            ImpulseLookbackBars = 4;
            MinOpeningRangeTicks = 8;
            MaxOpeningRangeTicks = 80;
            OpeningRangeBreakBufferTicks = 2;
            PullbackLookbackBars = 6;
            MinPullbackDepthTicks = 4;
            MaxPullbackDepthTicks = 24;
            PullbackMaxDistanceFromVwapTicks = 10;
            PullbackTouchEmaTicks = 3;
            MaxBarsAfterImpulse = 18;
            MaxBarsAfterPullback = 6;
            UseDeltaFilter = false;
            UseImbalanceFilter = false;
            DeltaVolumeFactor = 1.25;
            AtrStopMult = 0.40;
            StopBeyondPullbackTicks = 2;
            BreakEvenTriggerR = 0.80;
            TrailMode = ReclaimTrailMode.HalfStop;
            TrailTriggerR = 1.10;
            TimeStopBars = 5;
            MinProgressR = 0.25;
            EntryOffsetTicks = 1;
            EntryTimeoutBars = 2;
            RiskPerTradePct = 0.35;
            UserMaxContracts = 1;
            MaxOpenPositions = 1;
            DailyLossLimit = 60.0;
            WeeklyLossLimit = 150.0;
            MaxTradesPerDay = 6;
            HardMaxTradesPerDay = 8;
            MaxConsecutiveLosses = 3;
            PauseAfterConsecutiveLosses = 2;
            PauseMinutesAfterLosses = 15;
            RoundTurnCommission = 1.90;
            SlippageTicks = 1;
        }

        protected void LockGoldDefaults()
        {
            StartingCapital = 2000.0;
            BarsRequiredToTrade = 10;
            IntradayOnly = true;
            MaxContractsByCapital = 10;
            InstrumentStatus = "allowed";
            MarginSourceBroker = "NinjaTrader";
            TradeStartTime = 600;
            TradeEndTime = 930;
            ForceFlatTime = 1245;
            OpeningRangeStartTime = 600;
            OpeningRangeMinutes = 10;
            EmaFastPeriod = 9;
            EmaSlowPeriod = 34;
            AtrPeriod = 14;
            AdxPeriod = 14;
            MinAdx = 0.0;
            VolumeSmaPeriod = 20;
            MinVolumeFactor = 1.15;
            MinBodyRangePct = 0.45;
            MinCloseLocationPct = 0.60;
            VwapMode = SessionVwapMode.TypicalPrice;
            VwapDistanceThresholdTicks = 12;
            VwapSlopeLookback = 8;
            MinVwapSlopeTicks = 1.0;
            VwapReclaimBufferTicks = 1;
            VwapChopBandTicks = 3;
            VwapCrossLookback = 12;
            MaxVwapCrosses = 3;
            MinEmaSpreadTicks = 2;
            ImpulseLookbackBars = 4;
            MinImpulseMoveTicks = 12;
            MinOpeningRangeTicks = 6;
            MaxOpeningRangeTicks = 60;
            OpeningRangeBreakBufferTicks = 2;
            PullbackLookbackBars = 6;
            MinPullbackDepthTicks = 4;
            MaxPullbackDepthTicks = 20;
            PullbackMaxDistanceFromVwapTicks = 8;
            PullbackTouchEmaTicks = 2;
            MaxBarsAfterImpulse = 18;
            MaxBarsAfterPullback = 6;
            UseDeltaFilter = false;
            UseImbalanceFilter = false;
            DeltaVolumeFactor = 1.25;
            AtrStopMult = 0.45;
            StopMinTicks = 8;
            StopMaxTicks = 16;
            StopBeyondPullbackTicks = 2;
            RewardRiskRatio = 1.80;
            BreakEvenTriggerR = 0.80;
            TrailMode = ReclaimTrailMode.HalfStop;
            TrailTriggerR = 1.10;
            TimeStopBars = 5;
            MinProgressR = 0.25;
            EntryOffsetTicks = 1;
            EntryTimeoutBars = 2;
            RiskPerTradePct = 0.35;
            UserMaxContracts = 1;
            MaxOpenPositions = 1;
            DailyLossLimit = 60.0;
            WeeklyLossLimit = 150.0;
            MaxTradesPerDay = 4;
            HardMaxTradesPerDay = 6;
            MaxConsecutiveLosses = 3;
            PauseAfterConsecutiveLosses = 2;
            PauseMinutesAfterLosses = 15;
            RoundTurnCommission = 1.90;
            SlippageTicks = 1;
        }
    }
}
