// AI-SANDBOX strategy generated by NT-Analyzer AI Strategy Lab.
// AI Cell: AI-CELL-MGC-006
// Class:   NTAAiSandboxSessionEdgeBreakoutMgc006
// Instrument: MGC
// Session window (Pacific Time): 06:30 - 12:30
// Risk shell: SetStopLoss + SetProfitTarget + MaxDailyLoss + MaxTradesPerDay + force-flat at session end.
#region Using declarations
using System;
using NinjaTrader.Cbi;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.NinjaScript.Strategies;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class NTAAiSandboxSessionEdgeBreakoutMgc006 : Strategy
    {
        private double _dailyOpenPnl;
        private DateTime _currentSessionDate = DateTime.MinValue;
        private int _tradesToday;

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name                            = "NTAAiSandboxSessionEdgeBreakoutMgc006";
                Description                     = "AI sandbox strategy generated by NT-Analyzer AI Lab.";
                Calculate                       = Calculate.OnBarClose;
                EntriesPerDirection             = 1;
                EntryHandling                   = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy    = true;
                ExitOnSessionCloseSeconds       = 30;
                IsFillLimitOnTouch              = false;
                MaximumBarsLookBack             = MaximumBarsLookBack.TwoHundredFiftySix;
                OrderFillResolution             = OrderFillResolution.High;
                Slippage                        = 1;
                StartBehavior                   = StartBehavior.WaitUntilFlat;
                TimeInForce                     = TimeInForce.Gtc;
                TraceOrders                     = false;
                RealtimeErrorHandling           = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling              = StopTargetHandling.PerEntryExecution;
                IsInstantiatedOnEachOptimizationIteration = false;
                BarsRequiredToTrade             = 45;

                Quantity            = 1;
                StopLossTicks       = 20;
                ProfitTargetTicks   = 34;
                MaxDailyLoss        = 400;
                MaxTradesPerDay     = 3;
                BreakoutLookback    = 40;
                RoundTurnCommission = 1.90;
                SlippageTicks       = 1;
                SessionStartPT      = "06:30";
                SessionEndPT        = "12:30";
            }
            else if (State == State.Configure)
            {
                SetStopLoss(CalculationMode.Ticks, StopLossTicks);
                SetProfitTarget(CalculationMode.Ticks, ProfitTargetTicks);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < BarsRequiredToTrade) return;
            if (BarsInProgress != 0) return;

            if (Bars.IsFirstBarOfSession || _currentSessionDate.Date != Time[0].Date)
            {
                _currentSessionDate = Time[0].Date;
                _dailyOpenPnl = SystemPerformance.AllTrades.TradesPerformance.Currency.CumProfit;
                _tradesToday = 0;
            }

            var sessionPnl = SystemPerformance.AllTrades.TradesPerformance.Currency.CumProfit - _dailyOpenPnl;
            if (sessionPnl <= -MaxDailyLoss)
            {
                ForceFlat();
                return;
            }

            if (IsBeforeSessionStart())
            {
                return;
            }

            if (IsBeyondSessionEnd())
            {
                ForceFlat();
                return;
            }

            if (Position.MarketPosition != MarketPosition.Flat) return;
            if (_tradesToday >= MaxTradesPerDay) return;

            double hi = MAX(High, BreakoutLookback)[1];
            double lo = MIN(Low,  BreakoutLookback)[1];
            if (Close[0] > hi)
            {
                _tradesToday++;
                EnterLong(Quantity, "AI_Brk_L");
            }
            else if (Close[0] < lo)
            {
                _tradesToday++;
                EnterShort(Quantity, "AI_Brk_S");
            }
        }

        private void ForceFlat()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        private bool IsBeyondSessionEnd()
        {
            // AI sandbox: intraday only, no overnight. Hard cut-off at SessionEndPT.
            var pt = TimeZoneInfo.ConvertTimeFromUtc(Time[0].ToUniversalTime(),
                TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time"));
            var endParts = SessionEndPT.Split(':');
            int hh = int.Parse(endParts[0]);
            int mm = int.Parse(endParts[1]);
            return pt.Hour > hh || (pt.Hour == hh && pt.Minute >= mm);
        }

        private bool IsBeforeSessionStart()
        {
            var pt = TimeZoneInfo.ConvertTimeFromUtc(Time[0].ToUniversalTime(),
                TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time"));
            var startParts = SessionStartPT.Split(':');
            int hh = int.Parse(startParts[0]);
            int mm = int.Parse(startParts[1]);
            return pt.Hour < hh || (pt.Hour == hh && pt.Minute < mm);
        }

        #region Properties
        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int Quantity { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int StopLossTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int ProfitTargetTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int MaxDailyLoss { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int MaxTradesPerDay { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int BreakoutLookback { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public double RoundTurnCommission { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SlippageTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public string SessionStartPT { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public string SessionEndPT { get; set; }
        #endregion
    }
}
