// AI-SANDBOX strategy generated by NT-Analyzer AI Strategy Lab.
// AI Cell: AI-CELL-MNQ-035
// Class:   NTAAiSandboxVwapPullbackMnq035
// Instrument: MNQ
// Reference Pattern: REF-008
// Deterministic Family Renderer: vwap_liquidity_reversal
// Modification Hypothesis: MNQ VWAP liquidity reversal using 5m timeframe with RTH session (09:30-16:00 ET). Entry on 2nd pullback to VWAP after initial rejection, confirmed by volume spike and regime filter. Exit at 1.5x ATR or fixed target. Regime context ensures t
// Session window (Pacific Time): 06:30 - 12:30
// Risk shell: SetStopLoss + SetProfitTarget + MaxDailyLoss + MaxTradesPerDay + force-flat at session end.
#region Using declarations
using System;
using NinjaTrader.Cbi;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.NinjaScript.Strategies;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class NTAAiSandboxVwapPullbackMnq035 : Strategy
    {
        private double _dailyOpenPnl;
        private DateTime _currentSessionDate = DateTime.MinValue;
        private int _tradesToday;

        private double _sessionPriceVolume;
        private double _sessionVolume;


        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name                            = "NTAAiSandboxVwapPullbackMnq035";
                Description                     = "AI sandbox strategy generated by NT-Analyzer AI Lab.";
                Calculate                       = Calculate.OnBarClose;
                EntriesPerDirection             = 1;
                EntryHandling                   = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy    = true;
                ExitOnSessionCloseSeconds       = 30;
                IsFillLimitOnTouch              = false;
                MaximumBarsLookBack             = MaximumBarsLookBack.TwoHundredFiftySix;
                OrderFillResolution             = OrderFillResolution.High;
                Slippage                        = 1;
                StartBehavior                   = StartBehavior.WaitUntilFlat;
                TimeInForce                     = TimeInForce.Gtc;
                TraceOrders                     = false;
                RealtimeErrorHandling           = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling              = StopTargetHandling.PerEntryExecution;
                IsInstantiatedOnEachOptimizationIteration = false;
                BarsRequiredToTrade             = 55;

                Quantity            = 1;
                StopLossTicks       = 25;
                ProfitTargetTicks   = 40;
                MaxDailyLoss        = 400;
                MaxTradesPerDay     = 3;
                BreakoutLookback    = 50;
                RoundTurnCommission = 1.90;
                SlippageTicks       = 1;
                SessionStartTimePT  = 93000;
                SessionEndTimePT    = 160000;
            }
            else if (State == State.Configure)
            {
                SetStopLoss(CalculationMode.Ticks, StopLossTicks);
                SetProfitTarget(CalculationMode.Ticks, ProfitTargetTicks);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < BarsRequiredToTrade) return;
            if (BarsInProgress != 0) return;

            if (Bars.IsFirstBarOfSession || _currentSessionDate.Date != Time[0].Date)
            {
                _currentSessionDate = Time[0].Date;
                _dailyOpenPnl = SystemPerformance.AllTrades.TradesPerformance.Currency.CumProfit;
                _tradesToday = 0;

                _sessionPriceVolume = 0.0;
                _sessionVolume = 0.0;

            }


            double typicalPrice = (High[0] + Low[0] + Close[0]) / 3.0;
            _sessionPriceVolume += typicalPrice * Math.Max(1.0, Volume[0]);
            _sessionVolume += Math.Max(1.0, Volume[0]);

            var sessionPnl = SystemPerformance.AllTrades.TradesPerformance.Currency.CumProfit - _dailyOpenPnl;
            if (sessionPnl <= -MaxDailyLoss)
            {
                ForceFlat();
                return;
            }

            int nowPt = ToTime(Time[0]);
            if (nowPt < SessionStartTimePT)
            {
                return;
            }

            if (nowPt >= SessionEndTimePT)
            {
                ForceFlat();
                return;
            }

            if (Position.MarketPosition != MarketPosition.Flat) return;
            if (_tradesToday >= MaxTradesPerDay) return;


            if (_sessionVolume <= 0.0) return;
            double sessionVwap = _sessionPriceVolume / _sessionVolume;
            double avgVolume = 0.0;
            int volumeBars = Math.Min(20, CurrentBar);
            for (int i = 1; i <= volumeBars; i++)
                avgVolume += Volume[i];
            avgVolume /= Math.Max(1, volumeBars);
            bool volumeConfirmed = Volume[0] >= avgVolume * 1.20;

            if (volumeConfirmed && Low[0] < sessionVwap
                && Close[0] > sessionVwap && Close[0] > Open[0]
                && Close[1] <= sessionVwap)
            {
                _tradesToday++;
                EnterLong(Quantity, "AI_VWAP_L");
            }
            else if (volumeConfirmed && High[0] > sessionVwap
                && Close[0] < sessionVwap && Close[0] < Open[0]
                && Close[1] >= sessionVwap)
            {
                _tradesToday++;
                EnterShort(Quantity, "AI_VWAP_S");
            }

        }

        private void ForceFlat()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        #region Properties
        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int Quantity { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int StopLossTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int ProfitTargetTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int MaxDailyLoss { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int MaxTradesPerDay { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int BreakoutLookback { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public double RoundTurnCommission { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SlippageTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SessionStartTimePT { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SessionEndTimePT { get; set; }
        #endregion
    }
}
