// AI-SANDBOX strategy generated by NT-Analyzer AI Strategy Lab.
// AI Cell: AI-CELL-MGC-010
// Class:   NTAAiSandboxTrendPullbackMgc010
// Instrument: MGC
// Reference Pattern: REF-020
// Deterministic Family Renderer: trend_pullback
// Modification Hypothesis: MGC trend continuation pullback using EMA alignment, ADX filter, and ATR-based stops. Entry on price retracement to EMA20 after strong trend confirmation via EMA8/21/50 stack and ADX>20. Avoids choppy regimes with regime detection. Reduces false starts.
// Session window (Pacific Time): 06:30 - 12:30
// Risk shell: SetStopLoss + SetProfitTarget + MaxDailyLoss + MaxTradesPerDay + force-flat at session end.
#region Using declarations
using System;
using NinjaTrader.Cbi;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.NinjaScript.Strategies;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class NTAAiSandboxTrendPullbackMgc010 : Strategy
    {
        private double _dailyOpenPnl;
        private DateTime _currentSessionDate = DateTime.MinValue;
        private int _tradesToday;


        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name                            = "NTAAiSandboxTrendPullbackMgc010";
                Description                     = "AI sandbox strategy generated by NT-Analyzer AI Lab.";
                Calculate                       = Calculate.OnBarClose;
                EntriesPerDirection             = 1;
                EntryHandling                   = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy    = true;
                ExitOnSessionCloseSeconds       = 30;
                IsFillLimitOnTouch              = false;
                MaximumBarsLookBack             = MaximumBarsLookBack.TwoHundredFiftySix;
                OrderFillResolution             = OrderFillResolution.High;
                Slippage                        = 1;
                StartBehavior                   = StartBehavior.WaitUntilFlat;
                TimeInForce                     = TimeInForce.Gtc;
                TraceOrders                     = false;
                RealtimeErrorHandling           = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling              = StopTargetHandling.PerEntryExecution;
                IsInstantiatedOnEachOptimizationIteration = false;
                BarsRequiredToTrade             = 65;

                Quantity            = 1;
                StopLossTicks       = 20;
                ProfitTargetTicks   = 34;
                MaxDailyLoss        = 400;
                MaxTradesPerDay     = 3;
                BreakoutLookback    = 60;
                RoundTurnCommission = 1.90;
                SlippageTicks       = 1;
                SessionStartTimePT  = 63000;
                SessionEndTimePT    = 123000;
            }
            else if (State == State.Configure)
            {
                SetStopLoss(CalculationMode.Ticks, StopLossTicks);
                SetProfitTarget(CalculationMode.Ticks, ProfitTargetTicks);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < BarsRequiredToTrade) return;
            if (BarsInProgress != 0) return;

            if (Bars.IsFirstBarOfSession || _currentSessionDate.Date != Time[0].Date)
            {
                _currentSessionDate = Time[0].Date;
                _dailyOpenPnl = SystemPerformance.AllTrades.TradesPerformance.Currency.CumProfit;
                _tradesToday = 0;

            }


            var sessionPnl = SystemPerformance.AllTrades.TradesPerformance.Currency.CumProfit - _dailyOpenPnl;
            if (sessionPnl <= -MaxDailyLoss)
            {
                ForceFlat();
                return;
            }

            int nowPt = ToTime(Time[0]);
            if (nowPt < SessionStartTimePT)
            {
                return;
            }

            if (nowPt >= SessionEndTimePT)
            {
                ForceFlat();
                return;
            }

            if (Position.MarketPosition != MarketPosition.Flat) return;
            if (_tradesToday >= MaxTradesPerDay) return;


            double fast = EMA(9)[0];
            double slow = EMA(21)[0];
            if (fast > slow && Low[0] <= fast && Close[0] > fast && Close[0] > Open[0])
            {
                _tradesToday++;
                EnterLong(Quantity, "AI_PULLBACK_L");
            }
            else if (fast < slow && High[0] >= fast && Close[0] < fast && Close[0] < Open[0])
            {
                _tradesToday++;
                EnterShort(Quantity, "AI_PULLBACK_S");
            }

        }

        private void ForceFlat()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        #region Properties
        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int Quantity { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int StopLossTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int ProfitTargetTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int MaxDailyLoss { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int MaxTradesPerDay { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int BreakoutLookback { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public double RoundTurnCommission { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SlippageTicks { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SessionStartTimePT { get; set; }

        [NinjaTrader.NinjaScript.NinjaScriptProperty]
        public int SessionEndTimePT { get; set; }
        #endregion
    }
}
