"""Honest named-executor publication through native gateway and SF Social.

Disposable authenticated fixture owner, not a real user's registration. The
task/receipt/verification/approval/post are generated by the application, and
remain explicitly synthetic all the way into the existing Social store.
"""
from dataclasses import replace
import json
from types import SimpleNamespace
from uuid import uuid4

import pytest

from app import community
from app.ai_control_center import contracts as c, domain_gateway as gateway, test_executor
from app.ai_control_center.states import ContractError
from app.ai_control_center.social_publication import SocialPublicationService
from tests.test_agent_world_automation_revocation import world, human  # noqa: F401
from tests.test_external_agent_native_e2e import drain


@pytest.fixture
def publication(world, monkeypatch, tmp_path):
    monkeypatch.setenv(test_executor.ENV, world.workspace)
    path = tmp_path / "isolated-diagnostic-social.json"
    monkeypatch.setattr(community, "_store_path", lambda: path)
    auth, service = human(world)
    ctx = auth["context"]
    profile = service._put(ctx, {"description": "Diagnostic Social fixture"})
    persona = service._ensure(ctx, c.Persona, uuid4(), uuid4(), profile,
        display_name="Synthetic Social fixture", profile=profile)
    service._walk(ctx, persona, "active")
    model = gateway.mutate(auth, "models", "new", "connect", {"idempotency_key": "social-dev-connect",
        "payload": {"label": "Diagnostic connection", "provider": "deepseek", "model": "diagnostic-fixture",
                    "api_key": "synthetic-social-not-a-real-key", "persona_id": str(persona.header.entity_id)}})
    task = service.start_task(context=ctx, model_id=model["id"], payload={"rubric_key": "json_arithmetic"},
                             idempotency_key="social-dev-task")
    assert drain()
    result = service.task_detail(context=ctx, task_id=task["id"])
    assert result["synthetic"] is True and result["status"] == "succeeded"
    return SimpleNamespace(auth=auth, context=ctx, service=service, path=path, outcome=result["outcome_id"])


def prepare(env):
    return gateway.mutate(env.auth, "publications", "new", "prepare", {
        "idempotency_key": "social-dev-prepare", "payload": {"source_kind": "outcome", "source_id": env.outcome}})


def publish(env, prepared, **changes):
    payload = {"source_kind": "outcome", "source_id": env.outcome,
        "approved_snapshot_sha256": prepared["snapshot_sha256"], "text": "SYNTHETIC diagnostic only",
        "visibility": "private", "confirm_permanent": True, **changes}
    return gateway.mutate(env.auth, "publications", "new", "publish", {
        "expected_revision": prepared["source_revision"], "idempotency_key": "social-dev-publication", "payload": payload})


def test_verified_diagnostic_outcome_preview_confirmation_existing_social_and_replay(publication):
    env = publication
    before = env.path.read_bytes() if env.path.exists() else None
    prepared = prepare(env)
    assert (env.path.read_bytes() if env.path.exists() else None) == before
    snapshot = prepared["snapshot"]
    assert snapshot["synthetic"] is True and snapshot["quality_claim"] is False
    assert snapshot["diagnostic_mode"] == "named_development_executor"
    assert snapshot["source_kind"] == "synthetic_model_response"
    assert snapshot["external_call"] is snapshot["paid_call"] is False
    assert snapshot["cost_usd"] == 0 and set(snapshot["metrics"]) == {"Diagnostic checks"}
    assert snapshot["title"].startswith("SYNTHETIC")
    with pytest.raises(ContractError, match="permanent_confirmation_required"):
        publish(env, prepared, confirm_permanent=False)
    result = publish(env, prepared)
    assert result["published_to"] == "sf_social" and result["post"]["object"]["synthetic"] is True
    assert publish(env, prepared)["deduplicated"] is True
    public = json.dumps(result["post"]["object"])
    assert "synthetic-social-not-a-real-key" not in public
    assert '"response"' not in public and '"prompt"' not in public


def test_scope_withdrawal_after_preview_prevents_publication(publication, monkeypatch):
    prepared = prepare(publication)
    monkeypatch.setenv(test_executor.ENV, "")
    with pytest.raises(ContractError, match="receipt_mismatch"):
        publish(publication, prepared)
    assert not publication.path.exists()


def test_snapshot_tampering_is_rejected(publication):
    prepared = prepare(publication)
    with pytest.raises(ContractError, match="approved_snapshot_changed"):
        publish(publication, prepared, approved_snapshot_sha256="a" * 64)


def test_foreign_principal_or_workspace_cannot_prepare_diagnostic_source(publication):
    env = publication
    outsider = uuid4()
    contexts = (replace(env.context, user_uuid=outsider, actor=replace(env.context.actor, actor_id=outsider)),
                replace(env.context, scope=replace(env.context.scope, workspace_id="ws_foreign_social_diagnostic")))
    service = gateway.social(env.auth)
    for context in contexts:
        with pytest.raises(ContractError, match="source_not_found"):
            service.prepare(context=context, admit=lambda: True, source_kind="outcome", source_id=env.outcome)


@pytest.mark.parametrize("changes", [{"paid_call": True}, {"external_call": True}, {"cost_usd": 1},
    {"actual_model": "untrusted-model"}, {"executor": "untrusted-executor"}, {"source": "provider_response"}])
def test_diagnostic_receipt_cannot_launder_paid_external_or_unknown_executor(publication, monkeypatch, changes):
    original = SocialPublicationService._json
    def altered(self, context, reference):
        value = original(self, context, reference)
        return {**value, **changes} if value.get("source") == "local_test_executor" else value
    monkeypatch.setattr(SocialPublicationService, "_json", altered)
    with pytest.raises(ContractError, match="receipt_mismatch"):
        prepare(publication)
    assert not publication.path.exists()
